[buildPlans.Riosevka]
family = "Riosevka"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.Riosevka.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-j = "flat-hook-serifless"
capital-q = "horizontal-tailed"
capital-r = "standing-serifless"
capital-w = "straight-vertical-sides-serifless"
a = "double-storey-tailed"
b = "toothed-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-serifless"
i = "serifed"
j = "flat-hook-serifless"
l = "serifed"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook"
u = "toothed-serifless"
w = "straight-vertical-sides-serifless"
y = "straight-serifless"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-descending-serifless"
lower-lambda = "straight"
lower-mu = "toothed-serifless"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
one = "no-base-flat-top-serif"
two = "straight-neck-serifless"
four = "open-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
asterisk = "hex-high"
brace = "straight"
ampersand = "upper-open"
percent = "rings-continuous-slash"
question = "corner"
partial-derivative = "straight-bar"
micro-sign = "toothed-serifless"
lig-neq = "slightly-slanted-dotted"

[buildPlans.Riosevka.variants.italic]
capital-g = "toothed-serifless-hookless"
capital-i = "short-serifed"
capital-j = "flat-hook-serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-q = "crossing-curly-tailed"
capital-r = "standing-serifless"
capital-u = "toothed-serifless"
capital-w = "straight-serifless"
capital-z = "straight-serifless-with-crossbar"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner-serifless"
d = "toothed-serifless"
f = "flat-hook-tailed"
g = "single-storey-earless-corner"
i = "serifless"
j = "flat-hook-serifless"
k = "diagonal-tailed-cursive-serifless"
l = "tailed"
m = "tailed-serifless"
n = "tailed-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
r = "hookless-serifless"
t = "hookless"
u = "tailed-serifless"
v = "cursive-serifless"
w = "cursive-serifless"
x = "semi-chancery-curly"
y = "cursive-flat-hook-serifless"
z = "straight-serifless-with-crossbar"
lower-lambda = "tailed-turn"
lower-mu = "tailed-serifless"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
one = "no-base-flat-top-serif"
two = "straight-neck-serifless"
four = "open-serifless"
six = "straight-bar"
eight = "two-circles"
nine = "straight-bar"
percent = "rings-continuous-slash-also-connected"
question = "smooth"
micro-sign = "tailed-serifless"

[buildPlans.Riosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Riosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Riosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
